### ISSUE TITLE
Error when running with traefik 2.1

### ISSUE THREAD

**Issue by guyspr** [dniel/traefik-forward-auth0#154]
Hello,

I'm trying to setup your forward auth on traefik using the supplied example. However, I'm getting the following error when running the application. It seems it's trying to read some kind of header which is missing.
```
{
"error": "Parameter specified as non-null is null: method dniel.forwardauth.infrastructure.endpoints.AuthorizeEndpoint.authorize, parameter forwardedUriHeader"
}
```

Any idea what the cause of this issue is?

**Comment by dniel** [comment]
When Traefik forwards traffic to services behind, it sets some headers containing information about the original request
- X-Forwarded-For
- X-Forwarded-Host
- X-Forwarded-Port
- X-Forwarded-Proto
- X-Forwarded-Server
- X-Forwarded-Uri

If you set environment variable ENV to DEBUG for the forwardauth container, it should print lots of debug information, including all the incoming headers to the `authorize` command.

Most probably it is something with the configuration of Traefik and/or routing to the forwardauth endpoint. There is some settings for forwarded-headers in Traefik.

**Comment by qiuwei** [comment]
@guyspr I have encountered the same error. Did you manage to figure it out?

**Comment by guyspr** [comment]
@qiuwei Sadly not. Good luck!

**Comment by dniel** [comment]
@qiuwei hi, could you provide me your docker-compose for me to check your configurartion?

**Comment by qiuwei** [comment]
@dniel @guyspr 

It seems traefik 2 is not forwarding the headers required by forward-auth0 by default.

By adding 

```
--entryPoints.web.forwardedHeaders.insecure
--entryPoints.websecure.forwardedHeaders.insecure
```
to the config of traefik,
forward-auth0 works like a charm.

**Comment by dniel** [comment]
Be careful to enable external headers to forwardauth, its possible to forge headers to manipulate access. I think you are on the right track but I have configured forwarded headers on the Middleware itself like this https://traefik-forward-auth0.readthedocs.io/en/latest/examples/traefik2/file.html. 

Probably u should only accept headers from trusted ips.

**Comment by dniel** [comment]
I'll close this issue and will re-open if @qiuwei  or @guyspr need help with more investigation.
Thanx for the feedback @qiuwei !

**Comment by qiuwei** [comment]
@dniel I have already configured forward-auth as you described in the document.
```
- "traefik.http.middlewares.forward-auth.forwardauth.address=https://auth_host/authorize"
 - "traefik.http.middlewares.forward-auth.forwardauth.authresponseheaders=authorization, x-forwardauth-nickname, x-forwardauth-family-name, x-forwardauth-given-name, x-forwardauth-name, x-forwardauth-sub, x-forwardauth-email"
- "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"
```

However, if I do not have 
```
--entryPoints.web.forwardedHeaders.insecure
--entryPoints.websecure.forwardedHeaders.insecure
```
in the traefik config,  I get the error message.
```
{
"error": "Parameter specified as non-null is null: method dniel.forwardauth.infrastructure.endpoints.AuthorizeEndpoint.authorize, parameter forwardedUriHeader"
}
```

**Comment by qiuwei** [comment]
https://community.containo.us/t/forwardauth-does-not-pass-x-forwarded-uri/3277

It might be a problem with traefik 2.0 .

Edit:

After some digging, it seems there are some changes regarding the header forwarding from traefik 1.7 to traefik 2.0.  In short, In v1.7, forwarded-header on entrypoint is insecure by default: https://docs.traefik.io/v1.7/configuration/entrypoints/#forwarded-header
In v2.0, forwarded-header on entrypoint is secure by default: https://docs.traefik.io/routing/entrypoints/#forwarded-header

Please refer to 
https://github.com/containous/traefik/issues/5648
for further discussion.

@dniel Could you update the documentation and provide a full example with traefik 2.0? Thanks a lot!
