### ISSUE TITLE
multiple instances?

### ISSUE THREAD

**Issue by billimek** [dniel/traefik-forward-auth0#3]
Do you know if this will handle cookies & JWT tokens properly when running multiple replicas of the `traefik-forward-auth0` deployment?

**Comment by dniel** [comment]
If you configure different listening ports, cookie domains and different callbacks urls, it should work with multiple running deployments of the with back-end.

**Comment by dniel** [comment]
An improvement to the backend would be configurable cookie name per application, but right now the name of the time is hard coded unfortunately .

**Comment by dniel** [comment]
The forwardauth backend is stateless, does not hold any session of the users. It should work fine with any number of replicas I think. I have updated my configuration with 3 replicas now and it seems to work without trouble. Its running at https://www.dniel.se and is using the configuration found here https://github.com/dniel/manifests/blob/master/forwardauth.yaml

**Comment by billimek** [comment]
Awesome, thank you @dniel!
