### ISSUE TITLE
OpenID Connect support?

### ISSUE THREAD

**Issue by bigwheels16** [dniel/traefik-forward-auth0#36]
Does this app currently support OpenID Connect?  Or is there plans to support it in the future?

**Comment by dniel** [comment]
Right now it does only support the Auth0 service and it uses the OIDC compliant [Authorization Code grant](https://auth0.com/docs/api-auth/tutorials/authorization-code-grant) so the application could in the future be extended to support other oauth2 identity providers than Auth0.  Right now my main goal is to complete a feature complete version using Auth0 and iron out bugs.

**Comment by dniel** [comment]
I think I misread your question earlier in the morning. The application is hard coded to use Auth0 as identity provider but Auth0 is a certified [OpenID Connect provider](https://auth0.com/docs/api-auth/tutorials/adoption). 

The application requests an access token and a JWT id-token with user info by default and put them as session cookies in the browser. 
The branch named "claims" add support to extract configurable claims from the ID_TOKEN received from Auth0 after it has verified that the token is valid by issuer, domain, signature and audience and validity period. The extracted claims is added to the HTTP headers of the request and forwarded to the target web-application.

**Comment by bigwheels16** [comment]
oh so you do support OpenID Connect, because I believe the ID_TOKEN is only available with OpenID Connect and not with straight OAuth.  Great!
