### ISSUE TITLE
Consider hosting helm chart on the Helm Hub

### ISSUE THREAD

**Issue by billimek** [dniel/traefik-forward-auth0#85]
There is a [helm hub](https://hub.helm.sh/) for hosting various (packaged) helm charts.  It would be great if the helm chart for this could be hosted there too.  Instructions for adding a helm repo are [here](https://github.com/helm/hub/blob/master/Repositories.md).

**Comment by dniel** [comment]
I'll do some research to find out which helm hub that has got most traction for the moment.

**Comment by dniel** [comment]
done, pr created but not yet merged
